apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T04:01:39Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "11665"
  uid: b0383c31-b242-4127-b737-6a1b69dd868f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.181.204
  clusterIPs:
  - 10.99.181.204
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31878
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
